INSERT INTO AUTHOR (FIRST NAME, LAST NAME) VALUES ('Czeslaw', 'Milosz');
INSERT INTO AUTHOR (FIRST NAME, LAST NAME) VALUES ('Czeslaw', 'Milosz');
INSERT INTO AUTHOR (FIRST NAME, LAST NAME) VALUES ('Czeslaw', 'Milosz');
INSERT INTO AUTHOR (FIRST NAME, LAST NAME) VALUES ('Czeslaw', 'Milosz');



INSERT INTO BOOK (CATEGORY, BORROW, ISBN, PAGES, RELEASE_DATE, DESCRIPTION, TITLE, AUTHORID) VALUES (' ', ' ');
INSERT INTO BOOK (CATEGORY, BORROW, ISBN, PAGES, RELEASE_DATE, DESCRIPTION, TITLE, AUTHORID) VALUES (' ', ' ');
INSERT INTO BOOK (CATEGORY, BORROW, ISBN, PAGES, RELEASE_DATE, DESCRIPTION, TITLE, AUTHORID) VALUES (' ', ' ');
INSERT INTO BOOK (CATEGORY, BORROW, ISBN, PAGES, RELEASE_DATE, DESCRIPTION, TITLE, AUTHORID) VALUES (' ', ' ');

